# Generated by Django 3.2.4 on 2021-06-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='text',
            field=models.CharField(default=False, max_length=300),
            preserve_default=False,
        ),
    ]
